### ISSUE TITLE
Setting CLARISSE_IGNORED_LIBRARIES and CLARISSE_IGNORED_MODULES

### ISSUE THREAD

**Issue by alister-chowdhury** [Isotropix/r2c#1]
Hi,
We would like to specific libraries and modules to ignore (IX_PBR_*).

Currently the logic to set `CLARISSE_IGNORED_LIBRARIES ` and `CLARISSE_IGNORED_MODULES`.
https://github.com/Isotropix/r2c/blob/master/cmake/Setup.cmake#L14-L15
```cmake
set (CLARISSE_IGNORED_LIBRARIES IX_R2C)
set (CLARISSE_IGNORED_MODULES LAYER_R2C_SCENE REDSHIFT)
```

I believe a relatively simple way to allow this, would to simply change the above lines to:
```cmake
list (APPEND CLARISSE_IGNORED_LIBRARIES IX_R2C)
list (APPEND CLARISSE_IGNORED_MODULES LAYER_R2C_SCENE REDSHIFT)
```

Many thanks,
Alister

**Comment by ix-dcourtois** [comment]
Hi, thanks for reporting this ! It has been fixed in ce1afe739e8005638300fe437aab40434b2688f7
